site_name: xolv Samples, Demos, Docs
site_url: https://xolv.info/
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - AI ML Data Science: 
    - Overview: ./ai-ml-datascience/index.md
    - Jupyter Notebooks:
      - Set up Jupyter Notebook: ./ai-ml-datascience/notebook/startjupyterinenv.md
      - Set up secrets locally: ./ai-ml-datascience/notebook/setupsecrets.md
    - GPU:
      - Set up GPU on dev: ./ai-ml-datascience/gpu/setupnvidiadriver.md
    - Containers:
      - Jupyter Docker Stacks: ./ai-ml-datascience/containers/jupyterdockerstacks.md
      - Set up GPU for Podman: ./ai-ml-datascience/gpu/setupmlonwindows.md
      - Set up secrets on Podman: ./ai-ml-datascience/containers/setuptokensforcontainers.md
    - Keys and secrets:
      - Dotenv: ./ai-ml-datascience/notebook/setupsecrets.md
      - Keyring [GitHub]: https://github.com/brucedkyle/xolv-site/tree/main/nlm-pattern/keys/README.md
      - encpass [GitHub]: https://github.com/brucedkyle/xolv-site/tree/main/nlm-pattern/encpass-key/README.md
    - Pytorch:
      - Set up Pytorch: ./ai-ml-datascience/gpu/installpytorch.md
    - Tensorflow:
      - Set up Tensorflow [Medium]: https://towardsdatascience.com/tensorflow-gpu-installation-made-easy-use-conda-instead-of-pip-52e5249374bc
    - Samples:
      - OpenAI hello notebook [GitHub]: https://github.com/brucedkyle/xolv-site/blob/main/nlm-pattern/openai-helloworld/README.md
      - Text classification [GitHub]: https://github.com/brucedkyle/xolv-site/blob/main/nlm-pattern/text-classification/README.md
      - Build a local AI co-pilot [IBM]: https://developer.ibm.com/tutorials/awb-local-ai-copilot-ibm-granite-code-ollama-continue/
  - Deployment:
    - Overview: ./deploy/index.md
    - Containers:
      - Set up local Podman Image Registry [Red Hat]:  https://www.redhat.com/sysadmin/simple-container-registry
      - Deploy to local registry: ./deploy/deploytolocalregistry.md
      - Deploy to Azure:
          - Create Azure container registry (CLI) [Azure]: https://learn.microsoft.com/en-us/azure/container-instances/container-instances-tutorial-prepare-acr 
          - Deploy container to App Services [Azure]: https://learn.microsoft.com/en-us/azure/app-service/quickstart-custom-container?tabs=python&pivots=container-linux-vscode
      - Deploy to OpenShift: 
          - Using GitHub: ./deploy/deploycontaineropenshift.md
          - Without Dockerfile: ./deploy/deploycontainerwithoutDockerfile.md
    - Models:
      - Deploying Machine Learning Models [KD Nuggets]: https://www.kdnuggets.com/deploying-machine-learning-models-a-step-by-step-tutorial
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.share
  language: en
  icon: 
      repo: fontawesome/brands/github
      edit: material/pencil 
      view: material/eye
  logo: ./media/my-xolv.info.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      lang: en
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.smartsymbols
  - tables
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
copyright: Copyright &copy; 2023 xolv.co 