name: project
channels:
  - pytorch # to test cuda/gpu environment
  - conda-forge
  - nvidia
dependencies:
  - notebook
  # basic data analysis
  - numpy
  - pandas
  - seaborn
  # machine learning
  - scikit-learn
  # cuda
  - pytorch::pytorch 
  - torchvision 
  - torchaudio 
  - pytorch-cuda=12.1
  - nvidia::cudatoolkit
  # other system requirements
  - pip
  - python-dotenv # for environment variables 
  # optional for pip
  #- pip:
  #  - -r requirements.txt